# Generated by Django 5.2.10 on 2026-02-03 12:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Handle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('handle', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Handle must be 3-20 chars, lowercase letters/numbers/underscore only.', regex='^[a-z0-9_]{3,20}$')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handle', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
